export type MonsterClass
	= 'Ancient Artillery'
	| 'Archer'
	| 'Guard'
	| 'Imp'
	| 'Boss'
	| 'Cave Bear'
	| 'Cultist'
	| 'Deep Terror'
	| 'Earth Demon'
	| 'Flame Demon'
	| 'Frost Demon'
	| 'Giant Viper'
	| 'Harrower Infester'
	| 'Hound'
	| 'Shaman'
	| 'Living Bones'
	| 'Living Corpse'
	| 'Living Spirit'
	| 'Lurker'
	| 'Night Demon'
	| 'Ooze'
	| 'Rending Drake'
	| 'Savvas Icestorm'
	| 'Savvas Lavaflow'
	| 'Spitting Drake'
	| 'Stone Golem'
	| 'Sun Demon'
	| 'Scout'
	| 'Wind Demon'
	
	// XCOM
	| 'Officer'
	| 'Purifier'
	| 'Sectoid';
